const actions = {

    GET_APPOINTMENTS: "GET_APPOINTMENTS",
    UPDATE_APPOINTMENT: "UPDATE_APPOINTMENT",
    GET_BOOKED_APPOINTMENTS: "GET_BOOKED_APPOINTMENTS",
    SET_BOOKED_APPOINTMENTS: "SET_BOOKED_APPOINTMENTS",
    SET_APPOINTMENTS: "SET_APPOINTMENTS",
    SAVE_APPOINTMENTS: "SAVE_APPOINTMENTS",
    APPOINTMENTS_ERROR: "APPOINTMENTS_ERROR",
    GET_UPCOMING_DATE_APPOINTMENTS: "GET_UPCOMING_DATE_APPOINTMENTS",
    SET_UPCOMING_DATE_APPOINTMENTS: "SET_UPCOMING_DATE_APPOINTMENTS",
    SET_COMPLETED_DATE_APPOINTMENTS: "SET_COMPLETED_DATE_APPOINTMENTS",
    GET_COMPLETED_DATE_APPOINTMENTS: "GET_COMPLETED_DATE_APPOINTMENTS",
    SET_CANCELED_DATE_APPOINTMENTS: "SET_CANCELED_DATE_APPOINTMENTS",
    GET_CANCELED_DATE_APPOINTMENTS: "GET_CANCELED_DATE_APPOINTMENTS",
    CANCELED_APPOINTMENT: "CANCELED_APPOINTMENT",
    IS_CANCELED_APPOINTMENT: "IS_CANCELED_APPOINTMENT",


    APPOINTEMENTS_LOADING: "APPOINTEMENTS_LOADING",
    APPOINTMENTS_SUCCESS: "APPOINTMENTS_SUCCESS",

    CANCELE_BOOKING_MSG: "CANCELE_BOOKING_MSG",
}
export default actions