const actions = {

    GET_TIMESLOTS: "GET_TIMESLOTS",
    GET_TIMESLOTS_START_TIME_ARRAY: "GET_TIMESLOTS_START_TIME_ARRAY",
    SET_TIMESLOTS_START_TIME_ARRAY: "SET_TIMESLOTS_START_TIME_ARRAY",
    SET_TIMESLOTS: "SET_TIMESLOTS",
    SAVE_TIMESLOT: "SAVE_TIMESLOT",
    TIMESLOTERROR: "TIMESLOT_ERROR",

    TIMESLOT_LOADING: "TIMESLOT_LOADING",
    IS_SUCCESS: "IS_SUCCESS",
}
export default actions