const actions = {

    GET_CATEGORIES: "GET_CATEGORIES",
    SET_CATEGORIES: "SET_CATEGORIES",
    SAVE_CATEGORIS: "SAVE_CATEGORIS",
    DELETE_CATEGORIS: "DELETE_CATEGORIS",
    UPDATE_CATEGORIS: "UPDATE_CATEGORIS",
    CATEGORIES_ERROR: "CATEGORIES_ERROR",

    CATEGORIES_LOADING: "CATEGORIES_LOADING",
    CATEGORIES_SUCCESS: "CATEGORIES_SUCCESS",
}
export default actions