const actions = {
    SEND_OTP: "SEND_OTP",
    CONFIRM_OTP: "CONFIRM_OTP",
    IS_VERIFIED: "IS_VERIFIED",
    SET_MOBILE: "SET_MOBILE",
    OTP_SEND: "OTP_SEND",
    RESEND_OTP: "RESEND_OTP",
    SIGN_IN: "SIGN_IN",
    SIGN_OUT: "SIGN_OUT",
    SET_AUTH: "SET_AUTH",
    SET_STATE: "SET_STATE",
    AUTH_CLEAR: "AUTH_CLEAR",
    UPDATE_PROFILE: "UPDAT_PROFILE",
    AUTH_LOADING: "AUTH_LOADING",
    IS_LOGIN_WEB: "IS_LOGIN_WEB",
    AUTH_ERROR: "AUTH_ERROR",

}
export default actions