const actions = {

    SET_USER: "SET_USER",
    UPDATE_USER: "UPDATE_USER",
    SAVE_USER: "SAVE_USER",
    GET_USER_DETAIL: "GET_USER_DETAIL",
    GET_USER_DETAIL_EMAIL: "GET_USER_DETAIL_EMAIL",
    USER_ERROR: "USER_ERROR",
    USER_CLEAR: "USER_CLEAR",
    IS_USER_UPDATE: "IS_USER_UPDATE",
    USER_LOADING: "USER_LOADING",
    SET_EXPO_PUSH_TOKEN: "SET_EXPO_PUSH_TOKEN",
}
export default actions